FROM almalinux:9 
# it is continuously pinging google.com
# CMD ["ping","google.com"]
# ENTRYPOINT ["ping","google.com"]
# we can override CMD, we can't override ENTRYPOINT
CMD ["google.com"]
ENTRYPOINT ["ping"]
