ARG version
# default version is 8 if we pass any version it will take that
FROM almalinux:${version:-8}  
ARG NAME="Manoj" \
    PROFESSION="DevSecOPS Engineer"\
    COMPANY="BenditoSoftTech PvtLtd"  
RUN echo "My Name is ${NAME}, version is ${version}"
CMD ["sleep","200"]

